const store=require('../../platform/store');
const {SKILLS,SKILL,LANES}=require('../../core/skills');
const {makeRng}=require('../../core/problems');
const sess=require('../../core/session');
const scoring=require('../../core/scoring');
const growth=require('../../core/growth');
const qs=require('../../core/quests');
const tr=require('../../core/trophies');
const ul=require('../../core/unlocks');
const i18n=require('../../platform/i18n');

const fmtTime=ms=>{const s=Math.max(0,Math.floor(ms/1000));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};
function progress(){const st=store.load();if(!st.progress)st.progress=sess.emptyProgress();return st.progress}
function stats(){const st=store.load();if(!st.stats)st.stats=growth.statsFromHistory(st.history);return st.stats}
function decorateProblem(p,step,answers={}){
 const unit=72,cols=Math.max(1,p.cols||1),rows=Math.max(1,p.rows||1);
 const cells=(p.cells||[]).map((c,i)=>{const key=c.key||c.id||('c'+i);const val=answers[key]!=null?answers[key]:(c.text??'');return {...c,key,text:String(val),active:(p.steps&&p.steps[step]&&(p.steps[step].key===key||p.steps[step].cell===key)),style:`left:${(c.c||0)*100/cols}%;top:${(c.r||0)*unit}rpx;width:${(c.cs||1)*100/cols}%;height:${(c.rs||1)*unit}rpx;`}});
 const lines=(p.lines||[]).map((l,i)=>({key:'l'+i,style:`left:${(l.c||0)*100/cols}%;top:${((l.r||0)+.92)*unit}rpx;width:${(l.cs||cols)*100/cols}%;`}));
 return {cells,lines,sheetHeight:rows*unit+20};
}
Page({
 data:{screen:'title',modal:'',grades:[1,2,3,4,5,6],week:['日','一','二','三','四','五','六'],counts:[6,10,14],keys:['7','8','9','4','5','6','1','2','3','0'],trophyFilters:[{id:'all',name:'全部'},{id:'got',name:'已获得'},{id:'next',name:'未获得'},{id:'soon',name:'即将达成'}],N:10,ok:0,ng:0,combo:0,dopa:'0',clock:'0:00',clockLabel:'目标 2:40',settings:{}},
 onLoad(){this.rng=makeRng(Date.now());this.calDate=new Date();this.refreshTitle();const b=store.claimLogin();if(b){this.setData({modal:'bonus',bonusText:`已连续签到 ${b.run} 天`,bonusSlots:store.STICKERS.map((x,i)=>i+1===b.slot?'★':'○')})}},
 onUnload(){if(this.timer)clearInterval(this.timer)},
 refreshTitle(){const st=store.load(),p=progress(),q=this.getQuests(),m=tr.trophyMetrics({stats:stats(),prog:p,bestStreak:store.bestStreak(),stickers:(st.bonus||{}).total||0,crowns:Object.values((st.bonus||{}).stickers||{}).filter(x=>x==='crown').length,extra:{}});if(!st.trophies)st.trophies={got:{}};tr.evaluate(st.trophies,m);store.save();this.setData({settings:st.settings,N:st.settings.count,volume:Math.round(st.settings.volume*100),motion:Math.round((st.settings.motion==null?1:st.settings.motion)*100),reviewCount:(p.review||[]).length,levelSub:p.placed?'根据当前技能自动出题':'首次游玩将进行实力诊断测试',treeBadge:sess.frontier(p).length,trophyBadge:tr.earnedCount(st.trophies),collectBadge:ul.ITEMS.filter(x=>ul.isUnlocked(x,st.trophies.got)).length,quests:q.list.map(x=>({...x,text:i18n.questTextI18n(x,qs.questText(x))})),questReward:q.rewarded?'全部完成！':'',treeCount:SKILLS.filter(x=>sess.isMastered(p,x.id)).length+'/'+SKILLS.length,treeStars:'☆ '+SKILLS.reduce((a,x)=>a+sess.starsOf(p,x.id),0)});this.renderCalendar()},
 getQuests(){const st=store.load();if(!st.quests)st.quests={};const p=progress(),ss=SKILLS.map(x=>sess.stateOf(p,x.id));const ctx={count:st.settings.count,review:p.review.length,placed:!!p.placed,hasNew:ss.includes('new'),hasLearning:ss.includes('learning')||ss.includes('new'),extraOk:st.history.slice(-5).some(h=>h.extraOk!=null),avgCells:stats().cells&&stats().problems?stats().cells/stats().problems:2,rusty:sess.rustyOf(p),polishWeek:(st.quests.polishDays||[]).filter(d=>growth.daysBetween(d,store.dayKey())<7).length};if(qs.ensureDay(st.quests,store.dayKey(),ctx))store.save();return st.quests},
 questNote(ev){const q=this.getQuests();const done=qs.questEvent(q,ev);if(done.length&&qs.claimReward(q))store.addHammer(1);if(done.length)store.save()},
 renderCalendar(){const y=this.calDate.getFullYear(),m=this.calDate.getMonth(),first=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate(),sum=store.monthSummary(y,m),today=store.dayKey();const a=[];for(let i=0;i<first;i++)a.push({key:'e'+i});for(let d=1;d<=n;d++){const k=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;a.push({key:k,d,played:!!sum[k],today:k===today,sticker:store.stickerOn(k)})}this.setData({calendar:a,calTitle:i18n.monthYearText(y,m)})},
 prevMonth(){this.calDate=new Date(this.calDate.getFullYear(),this.calDate.getMonth()-1,1);this.renderCalendar()},nextMonth(){this.calDate=new Date(this.calDate.getFullYear(),this.calDate.getMonth()+1,1);this.renderCalendar()},
 openDay(e){const k=e.currentTarget.dataset.day;if(!k)return;const rec=store.load().history.filter(x=>x.day===k);this.setData({modal:'day',dayTitle:k+'的练习记录',dayRecords:rec})},
 goTitle(){this.stopTimer();this.setData({screen:'title'});this.refreshTitle()},openSettings(){this.setData({modal:'settings'})},openGuide(){wx.showModal({title:'欢迎来到多帕速算',content:'个性化闯关会根据当前技能自动出题；也可以按年级练习、查看技能树、成就与收藏。',showCancel:false});store.markGuideSeen()},
 closeModal(){this.setData({modal:''})},setLang(e){i18n.setLanguage(e.currentTarget.dataset.lang);this.refreshTitle()},setCount(e){store.updateSettings({count:Number(e.currentTarget.dataset.count)});this.refreshTitle()},setSound(e){store.updateSettings({sound:e.detail.value})},setVolume(e){store.updateSettings({volume:e.detail.value/100});this.setData({volume:e.detail.value})},setMotion(e){store.updateSettings({motion:e.detail.value/100});this.setData({motion:e.detail.value})},resetData(){wx.showModal({title:'全部重置',content:'确定清除所有游戏进度、成就与自定义设置？',success:r=>{if(r.confirm){store.reset();this.setData({modal:''});this.refreshTitle()}}})},
 openTree(){const p=progress(),rust=new Set(sess.rustyOf(p));const tree=SKILLS.map(x=>({id:x.id,grade:x.grade,lane:LANES[x.lane],name:i18n.skillName(x.id)||x.name,state:rust.has(x.id)?'rusty':sess.stateOf(p,x.id),stars:'☆'.repeat(sess.starsOf(p,x.id))}));this.setData({screen:'tree',tree})},
 skillInfo(e){const id=e.currentTarget.dataset.id,p=progress(),s=SKILL[id],n=sess.nextStar(p,id);this.practiceId=id;this.setData({modal:'skill',skillModal:{grade:s.grade,name:i18n.skillName(id)||s.name,stars:'☆'.repeat(sess.starsOf(p,id)),next:n?(i18n.nextStarI18n(n).text+' '+i18n.nextStarI18n(n).now):'☆5 达成！'}})},
 askRelock(e){this.relockId=e.currentTarget.dataset.id;this.setData({modal:'confirm'})},confirmRelock(){sess.relockSkill(progress(),this.relockId);store.save();this.setData({modal:''});this.openTree()},practiceSkill(){this.setData({modal:''});this.startPlan({mode:'practice',basic:Array(this.data.N).fill(this.practiceId),extra:()=>this.practiceId})},
 openTrophy(){const st=store.load(),m=tr.trophyMetrics({stats:stats(),prog:progress(),bestStreak:store.bestStreak(),stickers:(st.bonus||{}).total||0,crowns:Object.values((st.bonus||{}).stickers||{}).filter(x=>x==='crown').length,extra:{}});const series=tr.SERIES.map(s=>({key:s.key,title:i18n.trophySeriesTitle(s.key,s.title),items:s.items.map(t=>({...t,...i18n.trophyItemI18n(t),got:!!st.trophies?.got?.[t.id],value:tr.valueOf(m,t.metric)}))}));this.setData({screen:'trophy',trophySeries:series,trophyCount:tr.earnedCount(st.trophies)+'/'+tr.TROPHIES.length})},setTrophyFilter(){},
 openCollect(){const st=store.load(),got=st.trophies?.got||{},equip=st.equip||ul.defaultEquip();const collection=ul.ITEMS.map(x=>({...x,unlocked:ul.isUnlocked(x,got)}));this.setData({screen:'collect',collection,collectCount:collection.filter(x=>x.unlocked).length+'/'+collection.length,collectNow:Object.values(equip).join(' · ')})},equipItem(e){const id=e.currentTarget.dataset.id,st=store.load(),it=ul.ITEM[id];if(!it||!ul.isUnlocked(it,st.trophies?.got||{}))return;st.equip=st.equip||ul.defaultEquip();st.equip[it.cat]=id;store.save();this.openCollect()},
 startLevel(){this.startPlan(sess.levelPlan(progress(),store.settings().count,this.rng))},startGrade(e){const g=Number(e.currentTarget.dataset.grade);this.startPlan(sess.gradePlan(g,store.settings().count,this.rng))},startReview(){const p=progress(),items=(p.review||[]).slice(0,40);this.startPlan(sess.reviewPlan(items))},
 startPlan(plan){this.plan=plan;this.qi=0;this.runFirst=true;this.runMisses=0;this.score=0;this.dopaL=0;this.combo=0;this.started=Date.now();this.setData({screen:'play',N:plan.basic.length,ok:0,ng:0,combo:0,dopa:'0',pips:plan.basic.map((_,i)=>({i,done:false}))});this.nextProblem();this.startTimer()},
 nextProblem(){if(this.qi>=this.plan.basic.length)return this.finishBasic();const id=this.plan.pick?this.plan.pick():this.plan.basic[this.qi];this.skillId=id;this.problem=sess.problemFor(progress(),id,this.rng);this.step=0;this.answers={};this.firstTry=true;this.problemMisses=0;this.problemStart=Date.now();this.renderProblem()},
 renderProblem(){const p=this.problem,d=decorateProblem(p,this.step,this.answers),st=p.steps?.[this.step];this.setData({...d,qtitle:i18n.problemTitle(p.title||SKILL[this.skillId].name),qno:`第 ${this.qi+1} 题`,stepLabel:st?i18n.stepLabel(st.label||st.hint||''):'',stamp:'',mascotState:''})},
 keyTap(e){const key=String(e.currentTarget.dataset.key),st=this.problem.steps?.[this.step];if(!st)return;if(key==='Backspace')return;const want=String(st.digit??st.value??st.answer??'');if(key!==want){this.firstTry=false;this.problemMisses++;this.combo=0;this.runMisses++;this.setData({ng:this.data.ng+1,combo:0,stamp:'差一点',mascotState:'wrong'});try{wx.vibrateShort({type:'light'})}catch{};return}const cell=st.key||st.cell;if(cell)this.answers[cell]=key;this.combo++;const base=this.problem.steps.length?scoring.basicDopaL((this.step+1)/this.problem.steps.length)-scoring.basicDopaL(this.step/this.problem.steps.length):.02;this.dopaL=scoring.addDopa(this.dopaL,base,this.combo);this.step++;this.setData({combo:this.combo,comboMult:'×'+scoring.comboMult(this.combo).toFixed(1),dopa:scoring.fmtDopa(this.dopaL),stamp:'正确',mascotState:'correct'});if(this.step>=this.problem.steps.length)setTimeout(()=>this.problemDone(),180);else this.renderProblem()},
 problemDone(){const ms=Date.now()-this.problemStart,p=progress(),res=sess.recordResult(p,this.skillId,this.firstTry,sess.signature(this.problem),{ms,day:store.dayKey(),cells:this.problem.steps.length,misses:this.problemMisses});growth.noteSolve(stats(),{cells:this.problem.steps.length,firstTry:this.firstTry,misses:this.problemMisses,review:this.plan.mode==='review',combo:this.combo});this.questNote({type:'solve',firstTry:this.firstTry,review:this.plan.mode==='review',skill:this.skillId,skillState:sess.stateOf(p,this.skillId)});if(this.plan.answer)this.plan.answer(this.firstTry);if(this.firstTry)this.score+=scoring.BASIC_SCORE/this.data.N;this.qi++;const pips=this.data.pips.slice();if(pips[this.qi-1])pips[this.qi-1].done=true;this.setData({ok:this.data.ok+1,pips});store.save();this.nextProblem()},
 startTimer(){this.stopTimer();this.timer=setInterval(()=>this.setData({clock:fmtTime(Date.now()-this.started)}),250)},stopTimer(){if(this.timer){clearInterval(this.timer);this.timer=null}},
 finishBasic(){this.stopTimer();const elapsed=Date.now()-this.started,rate=this.data.ok?Math.round((this.data.ok/(this.data.ok+this.runMisses))*100):0;growth.notePlay(stats(),{mode:this.plan.mode,grade:this.plan.grade,day:store.dayKey(),timeMs:elapsed,dopaL:this.dopaL,firstRate:rate/100,weekday:new Date().getDay()});this.questNote({type:'play',mode:this.plan.mode});store.addRecord({mode:this.plan.mode,grade:this.plan.grade,score:Math.round(this.score),ok:this.data.ok,ng:this.runMisses,timeMs:elapsed,dopaL:this.dopaL,firstRate:rate/100,count:this.data.N});store.save();this.setData({screen:'result',resultTitle:this.plan.mode==='review'?'错题复习完成':'基础练习完成',score:Math.round(this.score),resultOk:this.data.ok,resultNg:this.runMisses,resultRate:rate,resultTime:fmtTime(elapsed),dopa:scoring.fmtDopa(this.dopaL)})},
 startExtra(){this.setData({screen:'final',resultTitle:'加时挑战结束'});this.goTitle()}
});